### ISSUE TITLE
TJ clear-sky model implementations use sin instead of sind

### ISSUE THREAD

**Issue by kandersolar** [JamieMBright/Engerer2-separation-model#2]
I think all three implementations of the TJ clear-sky model in this repo are flawed in that the arguments to `sin` are interpreted as radians but should be interpreted as degrees.  Here are the relevant lines of code:

https://github.com/JamieMBright/Engerer2-separation-model/blob/8749240e0b7834a828e6a7a44c28ba1414f58e61/Engerer2Separation.py#L128-L130

https://github.com/JamieMBright/Engerer2-separation-model/blob/8749240e0b7834a828e6a7a44c28ba1414f58e61/Engerer2Separation.m#L122-L124

https://github.com/JamieMBright/Engerer2-separation-model/blob/8749240e0b7834a828e6a7a44c28ba1414f58e61/Engerer2Separation.R#L97-L99

As an aside, I think the implementation in the `clear-sky-models` repo has the same problem: https://github.com/JamieMBright/clear-sky-models/blob/86fe607e9ba66226be6102895491b7d756473a7e/R/1-TJ.R#L26-L28

The `360/365` coefficient seems like it is intended to produce one period per year in degrees.  Treating it as radians introduces an undesirable amplitude variation of period ~6 days, as these two screenshots show:

![image](https://user-images.githubusercontent.com/57452607/147829062-b889ee6b-4320-4c3c-bae7-8f51d1c9e21e.png)

![image](https://user-images.githubusercontent.com/57452607/147829077-52214619-dcb5-41ea-ba95-989ac8e1ca9c.png)

Changing the `360`s to `2*np.pi` seems to resolve the issue in the python implementation.  I did not check the R or MATLAB versions.

As far as I can tell, these equations for A, k, and C do not come from the 1957 Threlkeld & Jordan paper but rather from G Masters' "Renewable and Efficient Electric Power Systems", which contains this example (Example 7.8).  It only gives the correct answer if the argument to `sin` is interpreted as degrees:

![image](https://user-images.githubusercontent.com/57452607/147829368-a25d0ffd-4d2c-4746-87b7-d4aa21507130.png)

**Comment by kandersolar** [comment]
Perhaps worth pointing out that the parameterization script has the same:
https://github.com/JamieMBright/Engerer2-separation-model/blob/d09b69d47682352e2299afb601991c39dc60fec5/ParameteriseEngerer2Separation.m#L141-L143

**Comment by adriesse** [comment]
Good detective work!  Clearly show the value of open source and code review.

**Comment by JamieMBright** [comment]
Yeah you are of course right. 
Thanks for finding this. I shall push a change now with the relevant updates.

**Comment by JamieMBright** [comment]
I have committed the changes to master. 
Thanks for the open collaborative spirit here. 
It might well be updating this to have a more consistent clear-sky model worldwide following a model from here: https://doi.org/10.1016/j.rser.2020.110087

**Comment by kandersolar** [comment]
Thanks @JamieMBright!  

I think there is unfortunately no such function `np.sind` (or at least my numpy doesn't have it).  So perhaps `np.sin(np.radians(...))` or `np.sin(np.pi/180 * ...))` should be used in the python example.  

What would you suggest about using the parameter values published in https://aip.scitation.org/doi/10.1063/1.5097014?  Would you be worried about error because of this issue in how the parameter values were optimized?

**Comment by JamieMBright** [comment]
Right you are.

Yeah to be honest it would be uncertain now. Changing this code and then using the same parameters could/likely will lead to adverse affects. It won't be catastrophic as you demonstrate the values produced simply have a subtle oscillation rather than anything wild. I would need to revisit/update this work, though the process/method is still identical. Sadly I don't have the data in as clean a format as I once had at my previous job. 

I believe sind is fine for both R and matlab. Changing the Python implementation to np.sin(np.deg2rad(...))

**Comment by AdamRJensen** [comment]
@JamieMBright Do you know if the coefficients in the 2015 paper were based on the same incorrect implementation of the clear-sky model?

May I also suggest that a message be placed in the readme file of the repository letting users know of this known issue / change?
